- name: 'Run cleanup script- oppgave 18'
  uses: azure/powershell@v1
  with:
    inlineScript: .\funcApp\cleanup.ps1
    azPSVersion: "latest"

- name: 'logout from azure'
  uses: azure/powershell@v1
  with:
    inlineScript: |
      Disconnect-AzAccount -Scope CurrentUser
      az logout
      az cache purge
      az account clear
    azPSVersion: "latest"