name: oppgave 16

on:
  push:
    # paths:
    #   - "/.gihub/workflows/oppgave16.yml"
    #   - "/src/oppgave10.ps"
  workflow_dispatch:

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory:  ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 


      - name: Run Blackjack script file
        run: .\.src\oppgave10.ps1 
  
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true